[pytest]
testpaths =
    src/tests

markers =
    smoke: mark tests as smoke suite for the mobile automation framework MVP.

log_file = logs/pytest.log
log_file_level = DEBUG

addopts =
    -p no:cacheprovider
